version: '3.8'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - app

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - webnet
    volumes:
      - .:/app
networks:
  webnet:
    driver: bridge
